<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBRxQlok\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBRxQlok/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBRxQlok.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBRxQlok\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBRxQlok\App_KernelDevDebugContainer([
    'container.build_hash' => 'BRxQlok',
    'container.build_id' => '9fd6df56',
    'container.build_time' => 1650013495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBRxQlok');
